import htmlElementCreator from '../../utils/elementFactory';
import ModalDetailsTable from './ModalDetailsTable';

function ModalDetails(game, humanPlayerGame, computerPlayerGame) {
  // console.log('adding details section')
  const detailsContainer = htmlElementCreator('div', {
    className: 'details',
  });

  const detailsHeading = htmlElementCreator(
    'h3',
    { className: 'details__heading' },
    'Detailed answers',
  );

  // TABLE GENERATED BY DIFFERENT COMPONENT
  const detailsTable = ModalDetailsTable(
    game,
    humanPlayerGame,
    computerPlayerGame,
  );

  detailsContainer.append(detailsHeading, detailsTable);
  return detailsContainer;
}

export default ModalDetails;
