import htmlElementCreator from '../../utils/htmlElementCreator';
import ModalDetailsTable from './ModalDetailsTable';

function ModalDetails(game, humanPlayerGame, computerPlayerGame) {
  const detailsContainer = htmlElementCreator('div', {
    class: 'details',
  });

  const detailsHeading = htmlElementCreator(
    'h3',
    { class: 'details__heading' },
    'Detailed answers',
  );

  // TABLE GENERATED BY DIFFERENT COMPONENT
  const detailsTable = ModalDetailsTable(
    game,
    humanPlayerGame,
    computerPlayerGame,
  );

  detailsContainer.append(detailsHeading, detailsTable);
  return detailsContainer;
}

export default ModalDetails;
