import elementFactory from '../../utils/elementFactory';
import ModalDetailsTable from './ModalDetailsTable';

function ModalDetails(game, humanPlayerGame, computerPlayerGame) {
  const detailsHeading = elementFactory(
    'h3',
    { className: 'details__heading' },
    'Detailed answers',
  );

  // TABLE GENERATED BY DIFFERENT COMPONENT
  const detailsTable = ModalDetailsTable(
    game,
    humanPlayerGame,
    computerPlayerGame,
  );

  const detailsContainer = elementFactory(
    'div',
    {
      className: 'details',
    },
    detailsHeading,
    detailsTable,
  );

  // detailsContainer.append(detailsHeading, detailsTable);
  return detailsContainer;
}

export default ModalDetails;
